// API.md 13.2 전체 오류 코드
// 화면 분기는 HTTP status가 아니라 이 code 기준으로 한다 (API.md 2.5, 9절)

export const ErrorCode = {
  // 현재 구현
  INVALID_REQUEST: "INVALID_REQUEST",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCESS_DENIED: "ACCESS_DENIED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  CONVERSATION_NOT_FOUND: "CONVERSATION_NOT_FOUND",
  MESSAGE_NOT_FOUND: "MESSAGE_NOT_FOUND",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  EMAIL_VERIFICATION_REQUIRED: "EMAIL_VERIFICATION_REQUIRED",
  INVALID_VERIFICATION_CODE: "INVALID_VERIFICATION_CODE",
  VERIFICATION_CODE_EXPIRED: "VERIFICATION_CODE_EXPIRED",
  VERIFICATION_RESEND_TOO_SOON: "VERIFICATION_RESEND_TOO_SOON",
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
  DIRECT_CONVERSATION_WITH_SELF: "DIRECT_CONVERSATION_WITH_SELF",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  // 신규 기능 (워크스페이스/첨부/AI/카드)
  WORKSPACE_NOT_FOUND: "WORKSPACE_NOT_FOUND",
  WORKSPACE_ACCESS_DENIED: "WORKSPACE_ACCESS_DENIED",
  WORKSPACE_OWNER_REQUIRED: "WORKSPACE_OWNER_REQUIRED",
  WORKSPACE_ALREADY_DELETED: "WORKSPACE_ALREADY_DELETED",
  INVITATION_INVALID: "INVITATION_INVALID",
  INVITATION_EXPIRED: "INVITATION_EXPIRED",
  INVITATION_EMAIL_MISMATCH: "INVITATION_EMAIL_MISMATCH",
  INVITATION_LIMIT_EXCEEDED: "INVITATION_LIMIT_EXCEEDED",
  ATTACHMENT_NOT_FOUND: "ATTACHMENT_NOT_FOUND",
  ATTACHMENT_ACCESS_DENIED: "ATTACHMENT_ACCESS_DENIED",
  FILE_SIZE_EXCEEDED: "FILE_SIZE_EXCEEDED",
  UNSUPPORTED_FILE_TYPE: "UNSUPPORTED_FILE_TYPE",
  ATTACHMENT_EXTRACTION_FAILED: "ATTACHMENT_EXTRACTION_FAILED",
  ATTACHMENT_UNREADABLE: "ATTACHMENT_UNREADABLE",
  AI_REVIEW_NOT_FOUND: "AI_REVIEW_NOT_FOUND",
  AI_REVIEW_FAILED: "AI_REVIEW_FAILED",
  AI_REVIEW_NOT_CONFIRMED: "AI_REVIEW_NOT_CONFIRMED",
  TIME_ZONE_REQUIRED: "TIME_ZONE_REQUIRED",
  UNDERSTANDING_CARD_NOT_FOUND: "UNDERSTANDING_CARD_NOT_FOUND",
  INVALID_CARD_STATE: "INVALID_CARD_STATE",
  OUTSIDE_RECIPIENT_WORK_HOURS: "OUTSIDE_RECIPIENT_WORK_HOURS",
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ApiErrorResponse {
  timestamp: string;
  status: number;
  code: ErrorCodeType | string;
  message: string;
  fieldErrors: Record<string, string>;
}

// 401이면 로그인 화면으로, 403은 권한부족 토스트로 (API.md 7절)
export function isAuthExpired(error: ApiErrorResponse): boolean {
  return error.code === ErrorCode.INVALID_CREDENTIALS;
}

export function isAccessDenied(error: ApiErrorResponse): boolean {
  return (
    error.code === ErrorCode.ACCESS_DENIED ||
    error.code === ErrorCode.WORKSPACE_ACCESS_DENIED ||
    error.code === ErrorCode.ATTACHMENT_ACCESS_DENIED
  );
}
